### ISSUE TITLE
Known memory leaks must be fixed

### ISSUE THREAD

**Issue by turboelk** [Defavlt/libslw#3]
There's at least one area where a memory leak (at shut-down) will [occur](https://github.com/Defavlt/libslw/blob/master/src/state.cpp#L65):
1. The function call entry point:

src/state.cpp:65

>   slw::State::entry_data_t *point = new slw::State::entry_data_t;

Do note that this the only heap-allocated stuff we have going on (AFAIK, at least). 

Anyway, this structure should be stack-allocated, and a reference should be kept in slw::State (to begin with).

~~Later refactorings should place the logic in `slw::State::registerfn` in a `slw::Call::Call(string_t, entry_t, void * = nullptr)` instead.~~

~~When the call go out of scope, it (`slw::Call::~Call`) should clean up after itself by un-register the function closure (otherwise `lua_pcall` won't be safe anymore, and we'll get a panic event, closing the application).~~

~~There might be other areas were stray references to objects (that should be EOL) exists. Valgrind could surely lend a hand...~~ ([see this issue](https://github.com/Defavlt/libslw/issues/6))

**Comment by Defavlt** [comment]
see also #6

**Comment by Defavlt** [comment]
#6
